import type {
  Category,
  InventoryLot,
  Location,
  MarketplaceStats,
  Seller,
} from "./types";

// Deterministic placeholder imagery — swap for real product/warehouse
// photography without touching any component prop shapes.
const img = (seed: string, w = 900, h = 700) =>
  `https://picsum.photos/seed/${seed}/${w}/${h}`;

export const categories: Category[] = [
  { id: "electronics", slug: "electronics", name: "Electronics", listingCount: 2840, imageUrl: img("lw-electronics") },
  { id: "fashion", slug: "fashion", name: "Fashion & Apparel", listingCount: 1962, imageUrl: img("lw-fashion") },
  { id: "home-furniture", slug: "home-furniture", name: "Home & Furniture", listingCount: 1477, imageUrl: img("lw-furniture") },
  { id: "beauty", slug: "beauty", name: "Beauty & Personal Care", listingCount: 1120, imageUrl: img("lw-beauty") },
  { id: "kitchen", slug: "kitchen", name: "Kitchen & Dining", listingCount: 894, imageUrl: img("lw-kitchen") },
  { id: "appliances", slug: "appliances", name: "Appliances", listingCount: 763, imageUrl: img("lw-appliances") },
  { id: "automotive", slug: "automotive", name: "Automotive", listingCount: 611, imageUrl: img("lw-automotive") },
  { id: "footwear", slug: "footwear", name: "Footwear", listingCount: 958, imageUrl: img("lw-footwear") },
  { id: "toys", slug: "toys", name: "Toys & Games", listingCount: 1305, imageUrl: img("lw-toys") },
  { id: "sports", slug: "sports", name: "Sports & Outdoors", listingCount: 872, imageUrl: img("lw-sports") },
  { id: "industrial", slug: "industrial", name: "Industrial Equipment", listingCount: 349, imageUrl: img("lw-industrial") },
  { id: "medical", slug: "medical", name: "Medical Equipment", listingCount: 214, imageUrl: img("lw-medical") },
  { id: "office", slug: "office", name: "Office Supplies", listingCount: 668, imageUrl: img("lw-office") },
  { id: "general", slug: "general", name: "General Merchandise", listingCount: 2196, imageUrl: img("lw-general") },
];

export const locations: Location[] = [
  { id: "dallas-tx", city: "Dallas", state: "Texas", stateCode: "TX", country: "USA", region: "South", dealCount: 1284 },
  { id: "newark-nj", city: "Newark", state: "New Jersey", stateCode: "NJ", country: "USA", region: "Northeast", dealCount: 942 },
  { id: "los-angeles-ca", city: "Los Angeles", state: "California", stateCode: "CA", country: "USA", region: "West", dealCount: 1536 },
  { id: "atlanta-ga", city: "Atlanta", state: "Georgia", stateCode: "GA", country: "USA", region: "South", dealCount: 736 },
  { id: "chicago-il", city: "Chicago", state: "Illinois", stateCode: "IL", country: "USA", region: "Midwest", dealCount: 654 },
  { id: "columbus-oh", city: "Columbus", state: "Ohio", stateCode: "OH", country: "USA", region: "Midwest", dealCount: 421 },
  { id: "phoenix-az", city: "Phoenix", state: "Arizona", stateCode: "AZ", country: "USA", region: "West", dealCount: 387 },
  { id: "miami-fl", city: "Miami", state: "Florida", stateCode: "FL", country: "USA", region: "South", dealCount: 509 },
];

export const sellers: Seller[] = [
  {
    id: "northbridge-liquidation",
    slug: "northbridge-liquidation",
    name: "Northbridge Liquidation Co.",
    logoUrl: img("lw-seller-northbridge", 200, 200),
    verified: true,
    location: "Dallas, TX",
    categories: ["Electronics", "Appliances"],
    activeListings: 214,
    activeUnits: 12400,
    responseRate: 98,
    rating: 4.8,
    reviewCount: 312,
    memberSince: "2019-03-11",
    description: "Specialists in electronics and appliance customer-return liquidation.",
  },
  {
    id: "meridian-returns",
    slug: "meridian-returns",
    name: "Meridian Returns Group",
    logoUrl: img("lw-seller-meridian", 200, 200),
    verified: true,
    location: "Newark, NJ",
    categories: ["Fashion & Apparel", "Footwear"],
    activeListings: 168,
    activeUnits: 8760,
    responseRate: 95,
    rating: 4.7,
    reviewCount: 201,
    memberSince: "2020-07-02",
  },
  {
    id: "westline-wholesale",
    slug: "westline-wholesale",
    name: "Westline Wholesale",
    logoUrl: img("lw-seller-westline", 200, 200),
    verified: true,
    location: "Los Angeles, CA",
    categories: ["Home & Furniture", "General Merchandise"],
    activeListings: 302,
    activeUnits: 21300,
    responseRate: 99,
    rating: 4.9,
    reviewCount: 458,
    memberSince: "2018-11-20",
  },
  {
    id: "summit-surplus",
    slug: "summit-surplus",
    name: "Summit Surplus Partners",
    logoUrl: img("lw-seller-summit", 200, 200),
    verified: true,
    location: "Atlanta, GA",
    categories: ["Industrial Equipment", "Office Supplies"],
    activeListings: 96,
    activeUnits: 4820,
    responseRate: 92,
    rating: 4.6,
    reviewCount: 129,
    memberSince: "2021-01-15",
  },
  {
    id: "harbor-overstock",
    slug: "harbor-overstock",
    name: "Harbor Overstock",
    logoUrl: img("lw-seller-harbor", 200, 200),
    verified: true,
    location: "Chicago, IL",
    categories: ["Kitchen & Dining", "Beauty & Personal Care"],
    activeListings: 187,
    activeUnits: 9640,
    responseRate: 97,
    rating: 4.8,
    reviewCount: 264,
    memberSince: "2019-09-08",
  },
  {
    id: "vantage-bulk",
    slug: "vantage-bulk",
    name: "Vantage Bulk Trading",
    logoUrl: img("lw-seller-vantage", 200, 200),
    verified: false,
    location: "Phoenix, AZ",
    categories: ["Toys & Games", "Sports & Outdoors"],
    activeListings: 74,
    activeUnits: 3150,
    responseRate: 88,
    rating: 4.4,
    reviewCount: 67,
    memberSince: "2022-04-30",
  },
];

function hoursFromNow(hours: number): string {
  return new Date(Date.now() + hours * 60 * 60 * 1000).toISOString();
}

function daysAgo(days: number): string {
  return new Date(Date.now() - days * 24 * 60 * 60 * 1000).toISOString();
}

export const listings: InventoryLot[] = [
  {
    id: "lot-iphone15pro-48",
    slug: "apple-iphone-15-pro-128gb-grade-a-48-units",
    title: "Apple iPhone 15 Pro 128GB",
    brand: "Apple",
    categoryId: "electronics",
    subcategory: "Smartphones",
    condition: "grade-a",
    images: [img("lw-p-iphone-1"), img("lw-p-iphone-2"), img("lw-p-iphone-3"), img("lw-p-iphone-4")],
    quantity: 48,
    lotSize: "single-pallet",
    locationId: "dallas-tx",
    sellerId: "northbridge-liquidation",
    saleFormat: "auction",
    retailValue: 42000,
    currentPrice: 18500,
    bidCount: 12,
    auctionEndsAt: hoursFromNow(4.53),
    shippingMethods: ["freight", "ltl"],
    description:
      "Grade A functional customer-return units, factory reset and tested for power and display integrity. Mixed carrier lock status — manifest includes full IMEI and grading breakdown.",
    conditionNotes: "Grade A: minimal cosmetic wear, fully functional, battery health 85%+.",
    manifest: [
      { sku: "IP15P-128-BLK", description: "iPhone 15 Pro 128GB Black Titanium", quantity: 22, unitRetail: 999, category: "Smartphones" },
      { sku: "IP15P-128-NAT", description: "iPhone 15 Pro 128GB Natural Titanium", quantity: 16, unitRetail: 999, category: "Smartphones" },
      { sku: "IP15P-128-BLU", description: "iPhone 15 Pro 128GB Blue Titanium", quantity: 10, unitRetail: 999, category: "Smartphones" },
    ],
    dateAdded: daysAgo(2),
    featured: true,
    wishlistCount: 84,
  },
  {
    id: "lot-dyson-vacuum-120",
    slug: "dyson-v15-detect-cordless-vacuum-120-units",
    title: "Dyson V15 Detect Cordless Vacuum",
    brand: "Dyson",
    categoryId: "appliances",
    subcategory: "Vacuums",
    condition: "customer-returns",
    images: [img("lw-p-dyson-1"), img("lw-p-dyson-2"), img("lw-p-dyson-3")],
    quantity: 120,
    lotSize: "multi-pallet",
    locationId: "columbus-oh",
    sellerId: "harbor-overstock",
    saleFormat: "buy-now",
    retailValue: 89880,
    currentPrice: 31200,
    shippingMethods: ["freight"],
    description:
      "Customer-return units from a major national retailer. Units are untested; expect a mix of like-new and units requiring minor repair. Full manifest available on request.",
    dateAdded: daysAgo(5),
    featured: true,
    wishlistCount: 41,
  },
  {
    id: "lot-nike-footwear-600",
    slug: "nike-assorted-footwear-overstock-600-units",
    title: "Nike Assorted Footwear Overstock",
    brand: "Nike",
    categoryId: "footwear",
    condition: "new",
    images: [img("lw-p-nike-1"), img("lw-p-nike-2"), img("lw-p-nike-3")],
    quantity: 600,
    lotSize: "truckload",
    locationId: "newark-nj",
    sellerId: "meridian-returns",
    saleFormat: "auction",
    retailValue: 54000,
    currentPrice: 21400,
    buyNowPrice: 27500,
    bidCount: 27,
    auctionEndsAt: hoursFromNow(19.2),
    shippingMethods: ["freight", "ltl"],
    description:
      "Brand new, unworn overstock footwear across running, training and lifestyle lines. Assorted sizes skewed toward men's 9-11. Original boxes included.",
    dateAdded: daysAgo(1),
    featured: true,
    wishlistCount: 112,
  },
  {
    id: "lot-kitchenaid-mixers-72",
    slug: "kitchenaid-stand-mixers-open-box-72-units",
    title: "KitchenAid Artisan Stand Mixers",
    brand: "KitchenAid",
    categoryId: "kitchen",
    condition: "open-box",
    images: [img("lw-p-kitchenaid-1"), img("lw-p-kitchenaid-2")],
    quantity: 72,
    lotSize: "single-pallet",
    locationId: "chicago-il",
    sellerId: "harbor-overstock",
    saleFormat: "buy-now",
    retailValue: 36000,
    currentPrice: 15800,
    shippingMethods: ["freight", "ltl", "parcel"],
    description:
      "Open-box units, mostly returned unused with original packaging opened for inspection. Assorted colors. Minor box damage on select units.",
    dateAdded: daysAgo(3),
    wishlistCount: 29,
  },
  {
    id: "lot-samsung-tv-30",
    slug: "samsung-65-qled-tv-grade-b-30-units",
    title: "Samsung 65\" QLED Smart TV",
    brand: "Samsung",
    categoryId: "electronics",
    subcategory: "Televisions",
    condition: "grade-b",
    images: [img("lw-p-samsungtv-1"), img("lw-p-samsungtv-2"), img("lw-p-samsungtv-3")],
    quantity: 30,
    lotSize: "single-pallet",
    locationId: "atlanta-ga",
    sellerId: "summit-surplus",
    saleFormat: "auction",
    retailValue: 32970,
    currentPrice: 9800,
    bidCount: 8,
    auctionEndsAt: hoursFromNow(1.1),
    shippingMethods: ["freight"],
    description:
      "Grade B units with light cosmetic wear to bezels; all screens tested for dead pixels and uniformity. Remotes and stands included on 80% of units.",
    dateAdded: daysAgo(4),
    wishlistCount: 53,
  },
  {
    id: "lot-patio-furniture-40",
    slug: "outdoor-patio-furniture-sets-40-units",
    title: "Outdoor Patio Furniture Sets",
    brand: "Hampton Bay",
    categoryId: "home-furniture",
    condition: "customer-returns",
    images: [img("lw-p-patio-1"), img("lw-p-patio-2")],
    quantity: 40,
    lotSize: "truckload",
    locationId: "phoenix-az",
    sellerId: "vantage-bulk",
    saleFormat: "quote",
    retailValue: 68000,
    currentPrice: 24000,
    shippingMethods: ["freight", "local-pickup"],
    description:
      "6-piece patio conversation sets, mixed condition customer returns. Some assembly required. Ideal for resale through outdoor/seasonal retail channels.",
    dateAdded: daysAgo(7),
    wishlistCount: 18,
  },
  {
    id: "lot-beauty-mixed-2000",
    slug: "mixed-beauty-personal-care-case-pack-2000-units",
    title: "Mixed Beauty & Personal Care Case Pack",
    brand: "Mixed Brands",
    categoryId: "beauty",
    condition: "new",
    images: [img("lw-p-beauty-1"), img("lw-p-beauty-2")],
    quantity: 2000,
    lotSize: "case-pack",
    locationId: "los-angeles-ca",
    sellerId: "westline-wholesale",
    saleFormat: "buy-now",
    retailValue: 41000,
    currentPrice: 12600,
    shippingMethods: ["ltl", "parcel"],
    description:
      "Brand-new sealed beauty and personal care overstock spanning skincare, haircare and cosmetics. Manifest available with unit-level SKU and retail pricing.",
    dateAdded: daysAgo(1),
    featured: true,
    wishlistCount: 67,
  },
  {
    id: "lot-office-chairs-150",
    slug: "ergonomic-office-chairs-refurbished-150-units",
    title: "Ergonomic Office Chairs",
    brand: "Steelcase",
    categoryId: "office",
    condition: "refurbished",
    images: [img("lw-p-office-1"), img("lw-p-office-2")],
    quantity: 150,
    lotSize: "truckload",
    locationId: "columbus-oh",
    sellerId: "summit-surplus",
    saleFormat: "buy-now",
    retailValue: 97500,
    currentPrice: 38900,
    shippingMethods: ["freight"],
    description:
      "Professionally refurbished ergonomic task chairs sourced from corporate downsizing. Cleaned, inspected and mechanically serviced.",
    dateAdded: daysAgo(6),
    wishlistCount: 22,
  },
  {
    id: "lot-toys-assorted-3500",
    slug: "assorted-toys-games-overstock-3500-units",
    title: "Assorted Toys & Games Overstock",
    brand: "Mixed Brands",
    categoryId: "toys",
    condition: "new",
    images: [img("lw-p-toys-1"), img("lw-p-toys-2")],
    quantity: 3500,
    lotSize: "truckload",
    locationId: "dallas-tx",
    sellerId: "northbridge-liquidation",
    saleFormat: "auction",
    retailValue: 87500,
    currentPrice: 26400,
    bidCount: 34,
    auctionEndsAt: hoursFromNow(28.4),
    shippingMethods: ["freight", "ltl"],
    description:
      "Brand-new sealed toy and game overstock ahead of seasonal reset. Broad assortment across major licensed and private-label brands.",
    dateAdded: daysAgo(2),
    wishlistCount: 96,
  },
  {
    id: "lot-medical-devices-25",
    slug: "portable-diagnostic-devices-grade-a-25-units",
    title: "Portable Diagnostic Devices",
    brand: "Omron",
    categoryId: "medical",
    condition: "grade-a",
    images: [img("lw-p-medical-1"), img("lw-p-medical-2")],
    quantity: 25,
    lotSize: "single-pallet",
    locationId: "atlanta-ga",
    sellerId: "summit-surplus",
    saleFormat: "quote",
    retailValue: 18750,
    currentPrice: 8200,
    shippingMethods: ["parcel", "ltl"],
    description:
      "Grade A portable diagnostic units, fully tested and calibrated. Documentation and compliance certificates included for qualified buyers.",
    dateAdded: daysAgo(9),
    wishlistCount: 14,
  },
  {
    id: "lot-power-tools-90",
    slug: "cordless-power-tool-combo-kits-90-units",
    title: "Cordless Power Tool Combo Kits",
    brand: "DeWalt",
    categoryId: "industrial",
    condition: "open-box",
    images: [img("lw-p-tools-1"), img("lw-p-tools-2")],
    quantity: 90,
    lotSize: "multi-pallet",
    locationId: "miami-fl",
    sellerId: "vantage-bulk",
    saleFormat: "auction",
    retailValue: 40500,
    currentPrice: 14200,
    bidCount: 19,
    auctionEndsAt: hoursFromNow(6.75),
    shippingMethods: ["freight", "ltl"],
    description:
      "Open-box combo kits with drill, impact driver, batteries and charger. Boxes opened for QA; contents complete and tested.",
    dateAdded: daysAgo(3),
    wishlistCount: 38,
  },
  {
    id: "lot-apparel-mixed-5000",
    slug: "mixed-apparel-liquidation-case-pack-5000-units",
    title: "Mixed Apparel Liquidation Case Pack",
    brand: "Mixed Brands",
    categoryId: "fashion",
    condition: "mixed",
    images: [img("lw-p-apparel-1"), img("lw-p-apparel-2")],
    quantity: 5000,
    lotSize: "truckload",
    locationId: "newark-nj",
    sellerId: "meridian-returns",
    saleFormat: "buy-now",
    retailValue: 125000,
    currentPrice: 33500,
    shippingMethods: ["freight"],
    description:
      "Department store liquidation spanning men's, women's and kids' apparel. Mixed seasonal assortment, majority new with tags.",
    dateAdded: daysAgo(4),
    wishlistCount: 71,
  },
];

export const marketplaceStats: MarketplaceStats = {
  inventoryValue: 184_000_000,
  activeLots: 12400,
  verifiedSellers: 540,
  categories: 35,
  cities: 62,
};

export const heroStats = [
  { label: "Active Listings", value: "12,000+" },
  { label: "Verified Sellers", value: "500+" },
  { label: "Product Categories", value: "35+" },
  { label: "Bulk Deals", value: "Updated Daily" },
];

export const popularSearches = [
  "Apple electronics pallets",
  "Customer returns Texas",
  "Nike footwear truckload",
  "Small appliances lot",
  "Home goods overstock",
];

export const trendingSearches = [
  "Grade A smartphones",
  "Beauty case packs",
  "Patio furniture liquidation",
  "Power tool combo kits",
];

export function getListingById(id: string) {
  return listings.find((l) => l.id === id || l.slug === id);
}

export function getSellerById(id: string) {
  return sellers.find((s) => s.id === id || s.slug === id);
}

export function getCategoryById(id: string) {
  return categories.find((c) => c.id === id || c.slug === id);
}

export function getLocationById(id: string) {
  return locations.find((l) => l.id === id);
}

export function getRelatedListings(listing: InventoryLot, limit = 4) {
  return listings
    .filter((l) => l.id !== listing.id && l.categoryId === listing.categoryId)
    .slice(0, limit);
}
